# -*- coding: utf-8 -*-
"""17_nov_cyp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0Pv399UyfJw4nFydhw3Maf73CxEl0th
"""

edad =15 
estatura = 1.67
a =10
b =3

c = 2 ** b
print ( c )
 
e = estatura * 2.0
print( e )

f = a / b
print(f)

g = a // b
print(g)

h = a % b
print( "h = ", h )

num = 11
print("Es par num ?", ) ()

ecuación = 9 + 7 * 8 - 36 / 5
print(ecuación)

ecuación = 0
ecucación = (9 + 7) * 8 - 36 / 5
print(ecuación)

ecuación = 9 + 7 * 8 - 36 / 5
print(ecuación)

ecuación = 0
ecucación = (9 + 7) * 8 - 36 / 5
print(ecuación)

costo_chetos = 7.0 
tienda_abierta = True
capital_en_bolsa = 10.0
se_compra = (costo_chetos < capital_en_bolsa) and (tienda_abierta == True)
print(se_compra)